"""Report writers for TrustLayer scan results."""

from __future__ import annotations

import json
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .models import ScanResult, Severity

_REPORT_SHARING_WARNING = """\
> **Before sharing this report:** It may contain sanitised evidence from your
> project files, including partial file paths, route names, and redacted
> credential patterns. Review all findings before distributing, especially
> outside your immediate team. TrustLayer redaction is best-effort and not
> guaranteed to remove all sensitive information.
"""

_SEVERITY_EMOJI = {
    Severity.HIGH: "🔴",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}

_COVERAGE_NOTE = """\
## Coverage and Limitations

TrustLayer uses lightweight, pattern-based heuristics. It is **not** a
professional security audit and cannot:

- Detect all classes of vulnerability
- Guarantee that redacted output contains no sensitive data
- Audit runtime behaviour, authentication logic, or business rules
- Replace manual code review or a penetration test

Findings are labelled with a **confidence** level:
- `observed` — pattern was directly matched
- `possible` — heuristic match that needs human confirmation
- `needs_verification` — context was ambiguous; review manually

Use this report as a starting checklist, not a compliance statement.
"""


def _severity_badge(s: Severity) -> str:
    return f"{_SEVERITY_EMOJI.get(s, '')} **{s.value.upper()}**"


def write_markdown(result: ScanResult, output_path: str) -> None:
    counts = result.counts_by_severity()
    total = len(result.findings)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []

    lines.append("# TrustLayer Scan Report\n")
    lines.append(_REPORT_SHARING_WARNING)
    lines.append(f"**Scanned:** `{result.target}`  ")
    lines.append(f"**Date:** {now}  ")
    lines.append(f"**Files scanned:** {result.scanned_files}  ")
    if result.skipped_files:
        lines.append(f"**Files skipped (binary/large):** {result.skipped_files}  ")
    if result.url_scan_enabled:
        lines.append(f"**URLs crawled:** {result.scanned_urls}  ")
    lines.append("")

    # Summary
    lines.append("## Automated Findings Summary\n")
    if total == 0:
        lines.append(
            "> No urgent automated patterns detected. Human review is still required "
            "before launch — automated scanning cannot catch all issues.\n"
        )
    else:
        lines.append(f"**Total findings:** {total}\n")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in Severity:
            lines.append(f"| {_severity_badge(sev)} | {counts[sev.value]} |")
        lines.append("")
        lines.append(
            "> **Automated findings score:** these results reflect pattern matches "
            "only. Each finding should be reviewed by a human before launch.\n"
        )

    lines.append(_COVERAGE_NOTE)

    # Findings
    if result.findings:
        lines.append("## Findings\n")
        for i, f in enumerate(result.findings, 1):
            lines.append(f"### {i}. {f.title}")
            lines.append("")
            lines.append(f"| Field | Value |")
            lines.append(f"|-------|-------|")
            lines.append(f"| **Check ID** | `{f.check_id}` |")
            lines.append(f"| **Severity** | {_severity_badge(f.severity)} |")
            lines.append(f"| **Confidence** | `{f.confidence.value}` |")
            lines.append(f"| **Source** | `{f.source}` |")
            lines.append(f"| **Ask a human before launch** | {'Yes ⚠️' if f.ask_human else 'No'} |")
            lines.append("")
            lines.append(f"**Explanation:** {f.explanation}")
            lines.append("")
            lines.append(f"**Who could use this if exposed:** {f.who_could_use}")
            lines.append("")
            lines.append(f"**What they may access:** {f.what_they_access}")
            lines.append("")
            lines.append(f"**Possible damage:** {f.possible_damage}")
            lines.append("")
            lines.append(f"**Likelihood:** {f.likelihood}")
            lines.append("")
            lines.append(f"**Fastest safe fix:** {f.fastest_fix}")
            lines.append("")
            if f.evidence:
                lines.append("**Evidence (sanitised):**")
                lines.append("```")
                lines.append(f.evidence)
                lines.append("```")
                lines.append("")

    # Errors
    if result.errors:
        lines.append("## Scan Errors\n")
        for err in result.errors:
            lines.append(f"- {err}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [TrustLayer](https://github.com/AshleyBlythe/TrustLayer) — "
                 "a FLARE Collective open-source build-literacy tool. Not a professional security audit.*")

    Path(output_path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_json(result: ScanResult, output_path: str) -> None:
    data = result.to_dict()
    data["generated_at"] = datetime.now(timezone.utc).isoformat()
    data["_warning"] = (
        "This file may contain sanitised evidence from your project. "
        "Review before sharing. TrustLayer redaction is best-effort and not guaranteed."
    )
    Path(output_path).write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
